<?php

declare(strict_types=1);

namespace Modules\Organization\Teams\Application\DTO;

use App\Core\DTO\BaseDTO;

/**
 * Immutable input for creating/updating a team.
 * When code is null it will be auto-generated by TeamCodeGeneratorService.
 */
final class TeamDTO extends BaseDTO
{
    public function __construct(
        public readonly string $company_id,
        public readonly string $name,
        public readonly ?string $code = null,
        public readonly ?string $leader_name = null,
        public readonly ?string $description = null,
        public readonly bool $is_active = true,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            company_id: (string) $data['company_id'],
            name: (string) $data['name'],
            code: self::nullableString($data, 'code'),
            leader_name: self::nullableString($data, 'leader_name'),
            description: self::nullableString($data, 'description'),
            is_active: (bool) ($data['is_active'] ?? true),
        );
    }

    /** @param array<string, mixed> $data */
    private static function nullableString(array $data, string $key): ?string
    {
        $v = $data[$key] ?? null;

        return ($v === null || $v === '') ? null : (string) $v;
    }
}
