<?php

declare(strict_types=1);

namespace Modules\Organization\BusinessAccounts\Application\DTO;

use App\Core\DTO\BaseDTO;

/**
 * Immutable input for creating/updating a business account.
 * When code is null it will be auto-generated by BusinessAccountCodeGeneratorService.
 */
final class BusinessAccountDTO extends BaseDTO
{
    public function __construct(
        public readonly string $company_id,
        public readonly string $name,
        public readonly string $provider,
        public readonly ?string $brand_id = null,
        public readonly ?string $code = null,
        public readonly string $status = 'active',
        public readonly ?string $description = null,
        public readonly ?string $logo = null,
        public readonly ?array $oauth_config = null,
        public readonly ?array $api_keys = null,
        public readonly ?array $webhook_config = null,
        public readonly ?array $sync_settings = null,
        public readonly ?array $external_metadata = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            company_id: (string) $data['company_id'],
            name: (string) $data['name'],
            provider: (string) $data['provider'],
            brand_id: self::nullableString($data, 'brand_id'),
            code: self::nullableString($data, 'code'),
            status: (string) ($data['status'] ?? 'active'),
            description: self::nullableString($data, 'description'),
            logo: self::nullableString($data, 'logo'),
            oauth_config: isset($data['oauth_config']) ? (array) $data['oauth_config'] : null,
            api_keys: isset($data['api_keys']) ? (array) $data['api_keys'] : null,
            webhook_config: isset($data['webhook_config']) ? (array) $data['webhook_config'] : null,
            sync_settings: isset($data['sync_settings']) ? (array) $data['sync_settings'] : null,
            external_metadata: isset($data['external_metadata']) ? (array) $data['external_metadata'] : null,
        );
    }

    /** @param array<string, mixed> $data */
    private static function nullableString(array $data, string $key): ?string
    {
        $v = $data[$key] ?? null;

        return ($v === null || $v === '') ? null : (string) $v;
    }
}
