/**
 * Centralized route path constants. Reference these instead of string literals.
 */
export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  organization: '/organization',
  companies: '/companies',
  brands: '/brands',
  branches: '/branches',
  inventoryProducts: '/inventory/products',
  products: '/products',
  rawMaterials: '/raw-materials',
  warehouses: '/warehouses',
  categories: '/categories',
  units: '/units',
  suppliers: '/suppliers',
  supplierDetail: '/suppliers/:id',
  purchaseOrders: '/purchase-orders',
  purchaseOrdersNew: '/purchase-orders/new',
  goodsReceipts: '/goods-receipts',
  goodsReceiptsNew: '/goods-receipts/new',
  stockLedger: '/stock-ledger',
  customers: '/customers',
  channels: '/channels',
  productMappings: '/product-mappings',
  orders: '/orders',
  ordersNew: '/orders/new',
  fulfillments: '/fulfillments',
  fulfillmentsNew: '/fulfillments/new',
  stockSyncLogs: '/stock-sync-logs',
  syncLogs: '/sync-logs',
  // Legacy BOM routes — kept for redirect compatibility
  boms: '/boms',
  bomsNew: '/boms/new',
  // Recipe routes (canonical home: Inventory)
  recipes: '/inventory/recipes',
  recipesNew: '/inventory/recipes/new',
  // Materials sub-sections
  packagingMaterials: '/inventory/packaging-materials',
  consumables: '/inventory/consumables',
  semiFinishedMaterials: '/inventory/semi-finished-materials',
  inventoryDashboard: '/inventory/dashboard',
  inventoryAbcClassifications: '/inventory/abc-classifications',
  inventoryCycleCountPlanner: '/inventory/cycle-count-planner',
  inventoryVarianceAnalytics: '/inventory/variance-analytics',
  inventoryWarehousePerformance: '/inventory/warehouse-performance',
  costPricingCenter: '/inventory/cost-management',
  costManagement: '/inventory/cost-management',
  costManagementPriceReview: '/inventory/cost-management/price-review',
  costManagementCostHistory: '/inventory/cost-management/cost-history',
  inventory: '/inventory',
  purchasing: '/purchasing',
  procurementHub: '/purchasing/hub',
  purchaseMaterials: '/purchasing/purchase-materials',
  materialRequests: '/purchasing/material-requests',
  purchases: '/purchasing/purchases',
  supplierInvoices: '/purchasing/supplier-invoices',
  receivingCenter: '/purchasing/receiving',
  supplierReturns: '/purchasing/supplier-returns',
  sales: '/sales',
  accounting: '/accounting',
  crm: '/crm',
  hr: '/hr',
  reports: '/reports',
  settings: '/settings',
  operationsDemandAnalysis: '/operations/demand-analysis',
  // Preparation OS
  preparationDashboard: '/operations/preparation',
  preparationWaves:     '/operations/preparation/waves',
  preparedPool:         '/operations/preparation/pool',
  preparationStations:  '/operations/preparation/stations',
  preparationAnalytics: '/operations/preparation/analytics',
  pos: '/pos',
  // Inventory Master Data
  inventoryCategories: '/inventory/master-data/categories',
  inventoryProductCategories: '/inventory/master-data/product-categories',
  inventoryMaterialCategories: '/inventory/master-data/material-categories',
  inventoryUnits: '/inventory/master-data/units',
  // Inventory Count Sessions
  inventoryCount: '/inventory/count',
  inventoryCountDetail: '/inventory/count/:id',
  // Waste Investigations & Warehouse Liabilities
  wasteInvestigations: '/inventory/waste-investigations',
  warehouseLiabilities: '/inventory/warehouse-liabilities',
  // Stock Transfers (placeholder — backend not yet implemented)
  stockTransfers: '/inventory/stock-transfers',
  // Organization — WP-ORG-002
  businessAccounts: '/business-accounts',
  teams: '/teams',
  // Organization — WP-ORG-003 (People & Access — ComingSoon)
  users: '/admin/users',
  userInvitations: '/admin/users/invitations',
  roles: '/admin/roles',
  orgSearch: '/organization/search',
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
