/**
 * Centralized route path constants. Reference these instead of string literals.
 */
export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  organization: '/organization',
  companies: '/companies',
  branches: '/branches',
  inventoryProducts: '/inventory/products',
  products: '/products',
  rawMaterials: '/raw-materials',
  warehouses: '/warehouses',
  categories: '/categories',
  units: '/units',
  suppliers: '/suppliers',
  supplierDetail: '/suppliers/:id',
  purchaseOrders: '/purchase-orders',
  purchaseOrdersNew: '/purchase-orders/new',
  goodsReceipts: '/goods-receipts',
  goodsReceiptsNew: '/goods-receipts/new',
  stockLedger: '/stock-ledger',
  customers: '/customers',
  channels: '/channels',
  productMappings: '/product-mappings',
  orders: '/orders',
  ordersNew: '/orders/new',
  fulfillments: '/fulfillments',
  fulfillmentsNew: '/fulfillments/new',
  stockSyncLogs: '/stock-sync-logs',
  syncLogs: '/sync-logs',
  boms: '/boms',
  bomsNew: '/boms/new',
  inventoryDashboard: '/inventory/dashboard',
  inventoryAbcClassifications: '/inventory/abc-classifications',
  inventoryCycleCountPlanner: '/inventory/cycle-count-planner',
  inventoryVarianceAnalytics: '/inventory/variance-analytics',
  inventoryWarehousePerformance: '/inventory/warehouse-performance',
  inventory: '/inventory',
  purchasing: '/purchasing',
  sales: '/sales',
  accounting: '/accounting',
  crm: '/crm',
  hr: '/hr',
  reports: '/reports',
  settings: '/settings',
  operationsDemandAnalysis: '/operations/demand-analysis',
  pos: '/pos',
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
