/**
 * Centralized route path constants. Reference these instead of string literals.
 */
export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  organization: '/organization',
  companies: '/companies',
  brands: '/brands',
  branches: '/branches',
  inventoryProducts: '/inventory/products',
  products: '/products',
  rawMaterials: '/raw-materials',
  warehouses: '/warehouses',
  categories: '/categories',
  units: '/units',
  suppliers: '/suppliers',
  supplierDetail: '/suppliers/:id',
  purchaseOrders: '/purchase-orders',
  purchaseOrdersNew: '/purchase-orders/new',
  goodsReceipts: '/goods-receipts',
  goodsReceiptsNew: '/goods-receipts/new',
  stockLedger: '/stock-ledger',
  customers: '/customers',
  customerDetail: '/customers/:customerId',
  channels: '/channels',
  productMappings: '/product-mappings',
  orders: '/orders',
  ordersNew: '/orders/new',
  fulfillments: '/fulfillments',
  fulfillmentsNew: '/fulfillments/new',
  stockSyncLogs: '/stock-sync-logs',
  syncLogs: '/sync-logs',
  // Legacy BOM routes — kept for redirect compatibility
  boms: '/boms',
  bomsNew: '/boms/new',
  // Recipe routes (canonical home: Inventory)
  recipes: '/inventory/recipes',
  recipesNew: '/inventory/recipes/new',
  // Materials sub-sections
  packagingMaterials: '/inventory/packaging-materials',
  consumables: '/inventory/consumables',
  semiFinishedMaterials: '/inventory/semi-finished-materials',
  inventoryDashboard: '/inventory/dashboard',
  inventoryAbcClassifications: '/inventory/abc-classifications',
  inventoryCycleCountPlanner: '/inventory/cycle-count-planner',
  inventoryVarianceAnalytics: '/inventory/variance-analytics',
  inventoryWarehousePerformance: '/inventory/warehouse-performance',
  costPricingCenter: '/inventory/cost-management',
  costManagement: '/inventory/cost-management',
  costManagementPriceReview: '/inventory/cost-management/price-review',
  costManagementCostHistory: '/inventory/cost-management/cost-history',
  inventory: '/inventory',
  purchasing: '/purchasing',
  procurementHub: '/purchasing/hub',
  purchaseMaterials: '/purchasing/purchase-materials',
  materialRequests: '/purchasing/material-requests',
  purchases: '/purchasing/purchases',
  supplierInvoices: '/purchasing/supplier-invoices',
  receivingCenter: '/purchasing/receiving',
  supplierReturns: '/purchasing/supplier-returns',
  sales: '/sales',
  accounting: '/accounting',
  crm: '/crm',
  hr: '/hr',
  reports: '/reports',
  settings: '/settings',
  // Fulfillment Wave Workspace (TASK-PREP-UI-003)
  waveWorkspace:        '/operations/preparation/wave-workspace',
  waveProductDemand:    '/operations/preparation/wave-workspace/products',
  waveRawMaterials:     '/operations/preparation/wave-workspace/materials',
  waveMissingMaterials: '/operations/preparation/wave-workspace/missing',
  waveOrders:           '/operations/preparation/wave-workspace/wave-orders',
  waveSettings:         '/operations/preparation/wave-workspace/settings',
  pos: '/pos',
  // Inventory Master Data
  inventoryCategories: '/inventory/master-data/categories',
  inventoryProductCategories: '/inventory/master-data/product-categories',
  inventoryMaterialCategories: '/inventory/master-data/material-categories',
  inventoryUnits: '/inventory/master-data/units',
  // Inventory Count Sessions
  inventoryCount: '/inventory/count',
  inventoryCountDetail: '/inventory/count/:id',
  // Waste Investigations & Warehouse Liabilities
  wasteInvestigations: '/inventory/waste-investigations',
  warehouseLiabilities: '/inventory/warehouse-liabilities',
  // Stock Transfers (placeholder — backend not yet implemented)
  stockTransfers: '/inventory/stock-transfers',
  // Organization — WP-ORG-002
  businessAccounts: '/business-accounts',
  teams: '/teams',
  // Organization — WP-ORG-003 (People & Access — ComingSoon)
  users: '/admin/users',
  userInvitations: '/admin/users/invitations',
  roles: '/admin/roles',
  orgSearch: '/organization/search',
  // Configuration OS
  configurationOs:      '/admin/configuration',
  configurationCompany: '/admin/configuration/company',
  configurationBrand:   '/admin/configuration/brands/:brandId',
  // Logistics OS
  logisticsGeography:            '/logistics/geography',
  logisticsDistributionZones:    '/logistics/distribution/zones',
  logisticsDistributionPlanning: '/logistics/distribution/planning',
  // Administration Master Data (legacy alias kept for redirect safety)
  egyptGeography: '/logistics/geography',
  // Marketing OS
  marketing:              '/marketing',
  marketingAssets:        '/marketing/assets',
  marketingConnectMeta:   '/marketing/connect/meta',
  marketingCampaigns:      '/marketing/campaigns',
  marketingCampaignDash:   '/marketing/campaigns/dashboard',
  marketingInitiatives:    '/marketing/initiatives',
  marketingInitiativeDash: '/marketing/initiatives/executive',
  // Campaign Studio
  campaignStudio:          '/marketing/studio',
  campaignStudioDraft:     '/marketing/studio/drafts/:draftId',
  campaignGovernance:      '/marketing/studio/governance',
  campaignStudioDashboard: '/marketing/studio/dashboard',
  // Core Platform — Business Attribution Engine
  businessAttribution: '/core/business-attribution',
  baeTimeline:         '/core/business-attribution/timeline',
  // Customer Engagement Platform
  customerEngagement:  '/customer-engagement',
  cepDashboard:        '/customer-engagement/dashboard',
  cepLeads:            '/customer-engagement/leads',
  // Omnichannel Commerce (MKT-007)
  omnichannelInbox:       '/omnichannel',
  omnichannelDashboard:   '/omnichannel/dashboard',
  omnichannelMacros:      '/omnichannel/macros',
  omnichannelRouting:     '/omnichannel/routing',
  omnichannelProviders:   '/omnichannel/providers',
  // Marketing Automation Platform
  automationWorkspace:    '/marketing/automation',
  workflowBuilder:        '/marketing/automation/workflows/:workflowId',
  audienceSegments:       '/marketing/automation/segments',
  automationDashboard:    '/marketing/automation/dashboard',
  automationGovernance:   '/marketing/automation/governance',
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
