<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * TASK-COST-ARCH-002 — Add immutable cost snapshot and explanation to pricing_reviews.
 *
 * cost_snapshot  — immutable JSON snapshot of cost state at review creation/update time.
 *                  Must never be modified after it is first written.
 * explanation    — human-readable text generated by CostImpactEngine describing the change.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('pricing_reviews', function (Blueprint $table): void {
            $table->json('cost_snapshot')->nullable()->after('trigger_source');
            $table->text('explanation')->nullable()->after('cost_snapshot');
        });
    }

    public function down(): void
    {
        Schema::table('pricing_reviews', function (Blueprint $table): void {
            $table->dropColumn(['cost_snapshot', 'explanation']);
        });
    }
};
