<?php

declare(strict_types=1);

namespace Modules\Organization\Brands\Application\DTO;

use App\Core\DTO\BaseDTO;

/**
 * Immutable input for creating/updating a brand.
 * When code is null it will be auto-generated by BrandCodeGeneratorService.
 */
final class BrandDTO extends BaseDTO
{
    public function __construct(
        public readonly string $company_id,
        public readonly string $name,
        public readonly ?string $code = null,
        public readonly ?string $slug = null,
        public readonly ?string $logo = null,
        public readonly ?string $description = null,
        public readonly bool $is_active = true,
        public readonly ?float $default_target_margin = null,
        public readonly ?float $default_markup = null,
        public readonly ?float $default_discount_pct = null,
    ) {}

    /** @param array<string, mixed> $data */
    public static function fromArray(array $data): self
    {
        return new self(
            company_id: (string) $data['company_id'],
            name: (string) $data['name'],
            code: self::nullable($data, 'code'),
            slug: self::nullable($data, 'slug'),
            logo: self::nullable($data, 'logo'),
            description: self::nullable($data, 'description'),
            is_active: (bool) ($data['is_active'] ?? true),
            default_target_margin: isset($data['default_target_margin']) && $data['default_target_margin'] !== null
                ? (float) $data['default_target_margin'] : null,
            default_markup: isset($data['default_markup']) && $data['default_markup'] !== null
                ? (float) $data['default_markup'] : null,
            default_discount_pct: isset($data['default_discount_pct']) && $data['default_discount_pct'] !== null
                ? (float) $data['default_discount_pct'] : null,
        );
    }

    /** @param array<string, mixed> $data */
    private static function nullable(array $data, string $key): ?string
    {
        $v = $data[$key] ?? null;

        return ($v === null || $v === '') ? null : (string) $v;
    }
}
